import torch, os
from matplotlib import pyplot as plt
import numpy as np
DATA_PATH = "artifacts/cluster_problem_train.pt"
def plot_clusters(X_clean, Y):
    X_np = X_clean.cpu().numpy()
    Y_np = Y.cpu().numpy()
    plt.figure(figsize=(6,6))
    plt.scatter(X_np[:,0], X_np[:,1], c=Y_np, cmap="coolwarm", alpha=0.6)
    plt.title("Clean clusters before nuisances")
    plt.xlabel("x"); plt.ylabel("y")
    plt.show()

def save_data(X_clean, X_nuis, Y, exist_ok=False):
    """
    Function for saving the data generated by generator function.
    Exits if the file already exists and overwriting is not allowed.
    Returns data dictionary.
    """
    data = {"X_clean": X_clean, "X_nuis": X_nuis, "Y": Y}

    if os.path.exists(DATA_PATH) and not exist_ok:
        print("Found existing dataset at {DATA_PATH}, exit.")
        return data

    os.makedirs(os.path.dirname(DATA_PATH), exist_ok=exist_ok)
    torch.save(data, DATA_PATH)
    print(f"Saved dataset at {DATA_PATH}")
    return data

